scalar Upload

type File {
  filename: String!
  mimetype: String!
  encoding: String!
}

input FileFilter {
  id: Int
  email: String
}
type Query {
  # This is only here to satisfy the requirement that at least one
  # field be present within the 'Query' type.  This example does not
  # demonstrate how to fetch uploads back.
  otherFields: Boolean!
}

type Mutation {
  # Multiple uploads are supported. See graphql-upload docs for details.
  singleUpload(filter: FileFilter!, file: Upload!): User!
}
