type Devotional {
  id: Int
  verse_key: String
  personality_of_god: String
  promise: String
  conditions_promise: String
  personal_applications: String
  sins_to_avoid: String
  personal_notes: String
  user: User
  book: Books
  chapter: Int
  verses: String
  creation_date: Date
  amount: Int
  amount_day: Int
}

input DevotionalInput {
  verse_key: String
  personality_of_god: String
  promise: String
  conditions_promise: String
  personal_applications: String
  sins_to_avoid: String
  personal_notes: String
  user_id: Int
  book_id: Int
  chapter: Int
  verses: String
  creation_date: Date
}

input DevotionalFilter {
  id: Int
  user_id: Int
}

type Query {
  devotional(filter: DevotionalFilter!): [Devotional]
}

type Mutation {
  newDevotional(data: DevotionalInput!): Devotional!
  editeDevotional(filter: DevotionalFilter!, data: DevotionalInput): Devotional!
  deleteDevotional(filter: DevotionalFilter!): Devotional!
}
