type VerseOfTheDay {
  id: Int
  book: Books
  chapter: Int
  first_verse: Int
  end_verse: Int
  reflection: String
  author: String
  user: User
  publication: Boolean
  creation_date: Date
  date_publication:Date

  verse: [Verse]
  
}

input VerseOfTheDayInput {
  book_id: Int
  chapter: Int
  first_verse: Int
  end_verse: Int
  publication: Boolean
  user_id: Int
  reflection: String
  author: String
  date_publication: Date

}

input VerseOfTheDayFilter {
  id: Int
  version_id: Int
  book_id: Int
  chapter: Int
  verse: Int
  creation_date: String
  date_publication: Date
  publication: Boolean
}

type Query {
  verseOfTheDay(filter: VerseOfTheDayFilter!): VerseOfTheDay
  verseOfTheDayEdit(filter: VerseOfTheDayFilter!): VerseOfTheDay
  versesOfTheDays: [VerseOfTheDay]
}

type Mutation {
  newVerseOfTheDay(data: VerseOfTheDayInput!): VerseOfTheDay!
    editVerseOfTheDay(
      filter: VerseOfTheDayFilter!
      data: VerseOfTheDayInput!
    ): VerseOfTheDay!
    deleteVerseOfTheDay(filter: VerseOfTheDayFilter!): VerseOfTheDay
}
