type Reflection {
  id: Int
  text: String
  author: String
  user_id: User
  publication: Boolean
  date_publication: Date
  creation_date: Date
}

input ReflectionInput {
  text: String
  author: String
  user_id: Int
  publication: Boolean
  date_publication: Date
}

input ReflectionFilter {
  text: String
  author: String
  user_id: Int
  publication: Boolean
  date_publication: Date
}

type Query {
  reflection(filter: ReflectionFilter!): Reflection
}
